#!/bin/sh
#
# Usage: extract <file>
# Description: extracts archived files / mounts disk images
#
# credit: https://nparikh.org/notes/zshrc.txt
extract() {
  if [ "$#" -ne 1 ]; then
    echo "Usage: extract <file>" >&2
    return 1
  fi

  archive=$1

  if [ -f "$archive" ]; then
    case "$archive" in
      *.tar.bz2) tar -jxvf "$archive" ;;
      *.tar.gz)  tar -zxvf "$archive" ;;
      *.bz2)     bunzip2 -- "$archive" ;;
      *.dmg)
        if ! command -v hdiutil >/dev/null 2>&1; then
          echo "hdiutil is required to mount '$archive'" >&2
          return 1
        fi

        hdiutil mount "$archive"
        ;;
      *.gz)      gunzip -- "$archive" ;;
      *.tar)     tar -xvf "$archive" ;;
      *.tbz2)    tar -jxvf "$archive" ;;
      *.tgz)     tar -zxvf "$archive" ;;
      *.zip)     unzip -- "$archive" ;;
      *.ZIP)     unzip -- "$archive" ;;
      *.pax)     pax -r < "$archive" ;;
      *.pax.Z)   uncompress -c -- "$archive" | pax -r ;;
      *.rar)
        if ! command -v unrar >/dev/null 2>&1; then
          echo "unrar is required to extract '$archive'" >&2
          return 1
        fi

        unrar x -- "$archive"
        ;;
      *.Z)       uncompress -- "$archive" ;;
      *)
        echo "'$archive' cannot be extracted/mounted via extract()" >&2
        return 1
        ;;
    esac
  else
    echo "'$archive' is not a valid file" >&2
    return 1
  fi
}
