cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'node'
brew 'python3'
brew 'ruby-build'
brew 'rbenv'
brew 'tmux'
brew 'unrar'

cask 'dropbox'
cask 'handbrake'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'skitch'
cask 'visual-studio-code'
cask 'wireshark'
